# defining smart brick related keywords
smart_brick_keywords = {
    "60691",
    "60692",
    "60693",
    "75420",
    "75421",
    "75422",
    "75423",
    "75424",
    "75425",
    "75426",
    "75427",
    "AI brick",
    "bricknet",
    "connected play",
    "digital brick",
    "digital play",
    "dumb brick",
    "dumbbrick",
    "fart brick",
    "fart minifig",
    "fart play",
    "fart tag",
    "fartbrick",
    "fartminifig",
    "fartplay",
    "farttag",
    "interactive brick",
    "smart brick",
    "smart compatibility",
    "smart compatible",
    "smart device",
    "smart feature",
    "smart fig",
    "smart function",
    "smart lego",
    "smart minifig",
    "smart play",
    "smart set",
    "smart star war",
    "smart starwar",
    "smart tag",
    "smart tile",
    "smartbrick",
    "smartlego",
    "smartminifig",
    "smartplay",
    "smarttag"
}

product_quality_feature_keywords = {

    "battery_keywords": {
        "battery",
        "charge",
        "charger",
        "corrode",
        "corrosion",
        "cycle",
        "dead",
        "deplete",
        "depletion",
        "die",
        "drain",
        "duration",
        "hour",
        "juice",
        "life cycle",
        "lifecycle",
        "lipo",
        "lithium",
        "longevity",
        "minute",
        "power",
        "recharge",
        "rechargeable"
    },

    "electronics_keywords": {
        "accelerometer",
        "antenna",
        "bluetooth",
        "cable",
        "camera",
        "chip",
        "circuit",
        "coil",
        "component",
        "electric",
        "electrical",
        "electronic",
        "firmware",
        "gyro",
        "gyroscope",
        "hardware",
        "microphone",
        "rfid",
        "sensor",
        "telemetry",
        "wire",
        "wiring"
    },

    "digital_functionality_keywords": {
        "activate",
        "android",
        "app",
        "app store",
        "bar code",
        "barcode",
        "bug",
        "buggy",
        "compatibility",
        "compatible",
        "connect",
        "connection",
        "connectivity",
        "crash",
        "datum",
        "defect",
        "defective",
        "delay",
        "detect",
        "digital",
        "disconnect",
        "distance",
        "distant",
        "download",
        "drop",
        "feature",
        "freeze",
        "froze",
        "function",
        "glitch",
        "google play",
        "install",
        "interact",
        "interaction",
        "interactivity",
        "internet",
        "io",
        "network",
        "nfc",
        "phone",
        "play experience",
        "play feature",
        "play store",
        "playability",
        "proximity",
        "react",
        "recognize",
        "register",
        "reliable",
        "reset",
        "responsive",
        "scan",
        "shake",
        "smartphone",
        "software",
        "tablet",
        "tech",
        "technology",
        "throw",
        "trigger",
        "update",
        "wi fi",
        "wifi",
        "wireless",
        "wirelessly"
    },

    "light_keywords": {
        "blink",
        "bright",
        "dim",
        "flash",
        "flicker",
        "flickery",
        "glow",
        "light",
        "light up",
        "lighting",
        "lightup"
    },

    "price_keywords": {
        "$",
        "afford",
        "cash",
        "cheap",
        "cheaper",
        "cost",
        "costly",
        "dollar",
        "euro",
        "expense",
        "expensive",
        "greed",
        "greediness",
        "money",
        "overpay",
        "overprice",
        "pay",
        "paywall",
        "pound",
        "price",
        "pricey",
        "pricy",
        "tax",
        "value",
        "£",
        "€"
    },

    "durability_keywords": {
        "break",
        "breakage",
        "clutch",
        "crack",
        "damage",
        "dent",
        "durability",
        "durable",
        "fall apart",
        "fall off",
        "faulty",
        "fracture",
        "fragile",
        "loose",
        "mismould",
        "rattle",
        "scratch",
        "sturdiness",
        "sturdy"
    },

    "safety_keywords": {
        "burn",
        "combust",
        "danger",
        "dangerous",
        "epilepsy",
        "epileptic",
        "explode",
        "explosive",
        "fire",
        "hazard",
        "malfunction",
        "overheat",
        "safety",
        "seisure",
        "seizure",
        "shock",
        "smoke",
        "unsafe",
        "wet"
    },

    "sound_keywords": {
        "audio",
        "beep",
        "dialogue",
        "grating",
        "hearable",
        "loud",
        "music",
        "noise",
        "noisy",
        "quiet",
        "screech",
        "silent",
        "sound",
        "soundscape",
        "speaker",
        "squeak",
        "synthesis",
        "synthesiser",
        "synthesizer",
        "voice",
        "volume"
    },

    "service_keywords": {
        "availability",
        "available",
        "booklet",
        "customer service",
        "guidance",
        "guide",
        "illustrate",
        "illustration",
        "instruct",
        "instruction",
        "manual",
        "stock",
        "support",
        "unavailable",
        "unclear",
        "usability",
        "usable",
        "useability",
        "useable",
        "user friendly",
        "warranty"
    }
}
product_quality_feature_keywords["smart_brick_keywords"] = smart_brick_keywords | {"the brick", "the tag"}